ldap_peoples/urls.py
from django.urls import path
from .views import *

app_name="ldap_peoples"

urlpatterns = [
    path('{}/import'.format(app_name),
         import_file, name='import_file'),
]

ldap_peoples/templates/change_form.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}

{% block extrahead %}{{ block.super }}
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
{{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-form{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
&rsaquo; {% if has_change_permission %}<a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %}
&rsaquo; {% if add %}{% blocktrans with name=opts.verbose_name %}Add {{ name }}{% endblocktrans %}{% else %}{{ original|truncatewords:"18" }}{% endif %}
</div>
{% endblock %}
{% endif %}


{% block content %}

<div id="content-main">
{% block object-tools %}
{% if change %}{% if not is_popup %}
  <ul class="object-tools">
    {% block object-tools-items %}
    <li>
        {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}
        <a href="{% add_preserved_filters history_url %}" class="historylink">{% trans "History" %}</a>
    </li>
    {% if has_absolute_url %}<li><a href="{{ absolute_url }}" class="viewsitelink">{% trans "View on site" %}</a></li>{% endif %}
    {% endblock %}
  </ul>
{% endif %}{% endif %}
{% endblock %}
<form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post" id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}

<!--
Aggiunto
-->
<div class="row">
{% submit_row %}
</div>

<div>
{% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1" />{% endif %}
{% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}" />{% endif %}
{% if save_on_top %}{% block submit_buttons_top %}{% submit_row %}{% endblock %}{% endif %}
{% if errors %}
    <p class="errornote">
    {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
    {{ adminform.form.non_field_errors }}
{% endif %}

{% block field_sets %}
{% for fieldset in adminform %}
  {% include "admin/includes/fieldset.html" %}
{% endfor %}
{% endblock %}

{% block after_field_sets %}{% endblock %}

{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
    {% include inline_admin_formset.opts.template %}
{% endfor %}
{% endblock %}

{% block after_related_objects %}{% endblock %}

{% block submit_buttons_bottom %}{% submit_row %}{% endblock %}

{% block admin_change_form_document_ready %}
    <script type="text/javascript"
            id="django-admin-form-add-constants"
            src="{% static 'admin/js/change_form.js' %}"
            {% if adminform and add %}
                data-model-name="{{ opts.model_name }}"
            {% endif %}>
    </script>
{% endblock %}

{# JavaScript for prepopulated fields #}
{% prepopulated_fields_js %}

</div>
</form></div>
{% endblock %}

ldap_peoples/templates/change_list.html
{% extends "admin/change_list.html" %}
{% load i18n admin_urls %}
{% load static %}

{% block extrastyle %}
    {{ block.super }}
    <style>
        .toggable {
                    padding: 8px 10px;
                    margin-bottom: 15px;
                    border-top: 1px solid #eee;
                    border-bottom: 1px solid #eee;
                    background: #f8f8f8;
                    color: #666;
                    margin-right: 280px;
                    width: auto;
                    }

        .file_submit {
                        border: 3px solid #ccc !important;
                        padding: 2px 10px;
                        margin: 0;
                        vertical-align: middle;
                        background: #fff;
                        box-shadow: 0 -15px 20px -10px rgba(0, 0, 0, 0.15) inset;
                        cursor: pointer;
                        color: #333;
                     }
    </style>
{% endblock %}

{% block object-tools-items %}
<!--
    <li>
        <a href="mylink/" class="historylink">{% trans "Import Entries" %}</a>
    </li>
-->
    {{ block.super }}
    {% if has_absolute_url %}
        <li>
            <a href="{% url 'admin:view_on_site' content_type_id original.pk %}" class="viewsitelink">{% trans "View on site" %}</a>
        </li>
    {% endif %}
{% endblock %}

{% block search %}
{{ block.super }}
<div>
    <h2 id="import_h" style="">{% trans "Import form" %}</h2>
    <div class="toggable">
        <form action="{% url 'ldap_peoples:import_file' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
<!--
            <label for="import_file">
                <img src="{% static "admin/img/icon-addlink.svg" %}" alt="{% trans "Import Entries" %}">
            </label>
-->
            <label for="import_file">{% trans "File to import" %}:
                <input type="file" name="file_to_import">
            </label>

            <label>{% trans "file format" %}:
                <select name="file_format" required="">
                  <option value="json">JSON</option>
                  <option value="ldif">LDIF</option>
                </select>
            </label>

            <input type="submit" class="file_submit" value="{% trans 'Import in LDAP' %}">
        </form>
    </div>
</div>
{% endblock %}